version: "3"
services:

  api:
    build:
      context: ./walmartapi
      dockerfile: Dockerfile
      target: prod
    image: sokar311/walmartapi
    container_name: walmart-api
    ports:
      - "8081:8081"
    environment:
       - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - database

  frontend:
    build:
      context: ./walmartfo
      dockerfile: Dockerfile
      target: prod
    image: sokar311/wallmartfo
    container_name: walmart-fo
    ports:
      - "8082:8082"
    environment:
       - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - api

  database:
    image: mongo:3.6.8
    container_name: mongodb-local
    environment:
      MONGO_INITDB_ROOT_USERNAME: productListUser
      MONGO_INITDB_ROOT_PASSWORD: productListPassword
  
  mongoseeder:
    image: mongo:3.6.8
    volumes:
      - ./database/01-products.json:/tmp/01-products.json:ro
    command: mongoimport --host database --username productListUser --password productListPassword --authenticationDatabase admin --db promotions --collection products --mode upsert --file /tmp/01-products.json
    depends_on:
      - database

